/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignedInRouteImport } from './routes/_signed-in'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignedInIndexRouteImport } from './routes/_signed-in/index'
import { Route as SignedInCoursesCourseIdRouteImport } from './routes/_signed-in/courses.$courseId'

const SignedInRoute = SignedInRouteImport.update({
  id: '/_signed-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignedInIndexRoute = SignedInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignedInRoute,
} as any)
const SignedInCoursesCourseIdRoute = SignedInCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => SignedInRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SignedInIndexRoute
  '/sign-in': typeof SignInRoute
  '/courses/$courseId': typeof SignedInCoursesCourseIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/': typeof SignedInIndexRoute
  '/courses/$courseId': typeof SignedInCoursesCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_signed-in': typeof SignedInRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_signed-in/': typeof SignedInIndexRoute
  '/_signed-in/courses/$courseId': typeof SignedInCoursesCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/courses/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in' | '/' | '/courses/$courseId'
  id:
    | '__root__'
    | '/_signed-in'
    | '/sign-in'
    | '/_signed-in/'
    | '/_signed-in/courses/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SignedInRoute: typeof SignedInRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_signed-in': {
      id: '/_signed-in'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SignedInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_signed-in/': {
      id: '/_signed-in/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SignedInIndexRouteImport
      parentRoute: typeof SignedInRoute
    }
    '/_signed-in/courses/$courseId': {
      id: '/_signed-in/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof SignedInCoursesCourseIdRouteImport
      parentRoute: typeof SignedInRoute
    }
  }
}

interface SignedInRouteChildren {
  SignedInIndexRoute: typeof SignedInIndexRoute
  SignedInCoursesCourseIdRoute: typeof SignedInCoursesCourseIdRoute
}

const SignedInRouteChildren: SignedInRouteChildren = {
  SignedInIndexRoute: SignedInIndexRoute,
  SignedInCoursesCourseIdRoute: SignedInCoursesCourseIdRoute,
}

const SignedInRouteWithChildren = SignedInRoute._addFileChildren(
  SignedInRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SignedInRoute: SignedInRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
