/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignedInRouteRouteImport } from './routes/_signed-in/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignedInIndexRouteImport } from './routes/_signed-in/index'
import { Route as SignedInCoursesCourseIdRouteImport } from './routes/_signed-in/courses/$courseId'

const SignedInRouteRoute = SignedInRouteRouteImport.update({
  id: '/_signed-in',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignedInIndexRoute = SignedInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignedInRouteRoute,
} as any)
const SignedInCoursesCourseIdRoute = SignedInCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => SignedInRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SignedInIndexRoute
  '/login': typeof LoginRoute
  '/courses/$courseId': typeof SignedInCoursesCourseIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof SignedInIndexRoute
  '/courses/$courseId': typeof SignedInCoursesCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_signed-in': typeof SignedInRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_signed-in/': typeof SignedInIndexRoute
  '/_signed-in/courses/$courseId': typeof SignedInCoursesCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/courses/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/courses/$courseId'
  id:
    | '__root__'
    | '/_signed-in'
    | '/login'
    | '/_signed-in/'
    | '/_signed-in/courses/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SignedInRouteRoute: typeof SignedInRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_signed-in': {
      id: '/_signed-in'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SignedInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_signed-in/': {
      id: '/_signed-in/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SignedInIndexRouteImport
      parentRoute: typeof SignedInRouteRoute
    }
    '/_signed-in/courses/$courseId': {
      id: '/_signed-in/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof SignedInCoursesCourseIdRouteImport
      parentRoute: typeof SignedInRouteRoute
    }
  }
}

interface SignedInRouteRouteChildren {
  SignedInIndexRoute: typeof SignedInIndexRoute
  SignedInCoursesCourseIdRoute: typeof SignedInCoursesCourseIdRoute
}

const SignedInRouteRouteChildren: SignedInRouteRouteChildren = {
  SignedInIndexRoute: SignedInIndexRoute,
  SignedInCoursesCourseIdRoute: SignedInCoursesCourseIdRoute,
}

const SignedInRouteRouteWithChildren = SignedInRouteRoute._addFileChildren(
  SignedInRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SignedInRouteRoute: SignedInRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
