/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignedInRouteRouteImport } from './routes/_signed-in/route'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignedInIndexRouteImport } from './routes/_signed-in/index'
import { Route as SignedInOrganizationsOrganizationIdIndexRouteImport } from './routes/_signed-in/organizations/$organizationId/index'
import { Route as SignedInOrganizationsOrganizationIdCoursesCourseIdIndexRouteImport } from './routes/_signed-in/organizations/$organizationId/courses/$courseId/index'
import { Route as SignedInOrganizationsOrganizationIdCoursesCourseIdLearnersLearnerIdRouteImport } from './routes/_signed-in/organizations/$organizationId/courses/$courseId/learners/$learnerId'

const SignedInRouteRoute = SignedInRouteRouteImport.update({
  id: '/_signed-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignedInIndexRoute = SignedInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignedInRouteRoute,
} as any)
const SignedInOrganizationsOrganizationIdIndexRoute =
  SignedInOrganizationsOrganizationIdIndexRouteImport.update({
    id: '/organizations/$organizationId/',
    path: '/organizations/$organizationId/',
    getParentRoute: () => SignedInRouteRoute,
  } as any)
const SignedInOrganizationsOrganizationIdCoursesCourseIdIndexRoute =
  SignedInOrganizationsOrganizationIdCoursesCourseIdIndexRouteImport.update({
    id: '/organizations/$organizationId/courses/$courseId/',
    path: '/organizations/$organizationId/courses/$courseId/',
    getParentRoute: () => SignedInRouteRoute,
  } as any)
const SignedInOrganizationsOrganizationIdCoursesCourseIdLearnersLearnerIdRoute =
  SignedInOrganizationsOrganizationIdCoursesCourseIdLearnersLearnerIdRouteImport.update(
    {
      id: '/organizations/$organizationId/courses/$courseId/learners/$learnerId',
      path: '/organizations/$organizationId/courses/$courseId/learners/$learnerId',
      getParentRoute: () => SignedInRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof SignedInIndexRoute
  '/sign-in': typeof SignInRoute
  '/organizations/$organizationId/': typeof SignedInOrganizationsOrganizationIdIndexRoute
  '/organizations/$organizationId/courses/$courseId/': typeof SignedInOrganizationsOrganizationIdCoursesCourseIdIndexRoute
  '/organizations/$organizationId/courses/$courseId/learners/$learnerId': typeof SignedInOrganizationsOrganizationIdCoursesCourseIdLearnersLearnerIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/': typeof SignedInIndexRoute
  '/organizations/$organizationId': typeof SignedInOrganizationsOrganizationIdIndexRoute
  '/organizations/$organizationId/courses/$courseId': typeof SignedInOrganizationsOrganizationIdCoursesCourseIdIndexRoute
  '/organizations/$organizationId/courses/$courseId/learners/$learnerId': typeof SignedInOrganizationsOrganizationIdCoursesCourseIdLearnersLearnerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_signed-in': typeof SignedInRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_signed-in/': typeof SignedInIndexRoute
  '/_signed-in/organizations/$organizationId/': typeof SignedInOrganizationsOrganizationIdIndexRoute
  '/_signed-in/organizations/$organizationId/courses/$courseId/': typeof SignedInOrganizationsOrganizationIdCoursesCourseIdIndexRoute
  '/_signed-in/organizations/$organizationId/courses/$courseId/learners/$learnerId': typeof SignedInOrganizationsOrganizationIdCoursesCourseIdLearnersLearnerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/organizations/$organizationId/'
    | '/organizations/$organizationId/courses/$courseId/'
    | '/organizations/$organizationId/courses/$courseId/learners/$learnerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/'
    | '/organizations/$organizationId'
    | '/organizations/$organizationId/courses/$courseId'
    | '/organizations/$organizationId/courses/$courseId/learners/$learnerId'
  id:
    | '__root__'
    | '/_signed-in'
    | '/sign-in'
    | '/_signed-in/'
    | '/_signed-in/organizations/$organizationId/'
    | '/_signed-in/organizations/$organizationId/courses/$courseId/'
    | '/_signed-in/organizations/$organizationId/courses/$courseId/learners/$learnerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SignedInRouteRoute: typeof SignedInRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_signed-in': {
      id: '/_signed-in'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SignedInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_signed-in/': {
      id: '/_signed-in/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SignedInIndexRouteImport
      parentRoute: typeof SignedInRouteRoute
    }
    '/_signed-in/organizations/$organizationId/': {
      id: '/_signed-in/organizations/$organizationId/'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId/'
      preLoaderRoute: typeof SignedInOrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof SignedInRouteRoute
    }
    '/_signed-in/organizations/$organizationId/courses/$courseId/': {
      id: '/_signed-in/organizations/$organizationId/courses/$courseId/'
      path: '/organizations/$organizationId/courses/$courseId'
      fullPath: '/organizations/$organizationId/courses/$courseId/'
      preLoaderRoute: typeof SignedInOrganizationsOrganizationIdCoursesCourseIdIndexRouteImport
      parentRoute: typeof SignedInRouteRoute
    }
    '/_signed-in/organizations/$organizationId/courses/$courseId/learners/$learnerId': {
      id: '/_signed-in/organizations/$organizationId/courses/$courseId/learners/$learnerId'
      path: '/organizations/$organizationId/courses/$courseId/learners/$learnerId'
      fullPath: '/organizations/$organizationId/courses/$courseId/learners/$learnerId'
      preLoaderRoute: typeof SignedInOrganizationsOrganizationIdCoursesCourseIdLearnersLearnerIdRouteImport
      parentRoute: typeof SignedInRouteRoute
    }
  }
}

interface SignedInRouteRouteChildren {
  SignedInIndexRoute: typeof SignedInIndexRoute
  SignedInOrganizationsOrganizationIdIndexRoute: typeof SignedInOrganizationsOrganizationIdIndexRoute
  SignedInOrganizationsOrganizationIdCoursesCourseIdIndexRoute: typeof SignedInOrganizationsOrganizationIdCoursesCourseIdIndexRoute
  SignedInOrganizationsOrganizationIdCoursesCourseIdLearnersLearnerIdRoute: typeof SignedInOrganizationsOrganizationIdCoursesCourseIdLearnersLearnerIdRoute
}

const SignedInRouteRouteChildren: SignedInRouteRouteChildren = {
  SignedInIndexRoute: SignedInIndexRoute,
  SignedInOrganizationsOrganizationIdIndexRoute:
    SignedInOrganizationsOrganizationIdIndexRoute,
  SignedInOrganizationsOrganizationIdCoursesCourseIdIndexRoute:
    SignedInOrganizationsOrganizationIdCoursesCourseIdIndexRoute,
  SignedInOrganizationsOrganizationIdCoursesCourseIdLearnersLearnerIdRoute:
    SignedInOrganizationsOrganizationIdCoursesCourseIdLearnersLearnerIdRoute,
}

const SignedInRouteRouteWithChildren = SignedInRouteRoute._addFileChildren(
  SignedInRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SignedInRouteRoute: SignedInRouteRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
