/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignedInRouteRouteImport } from './routes/_signed-in/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SignedInIndexRouteImport } from './routes/_signed-in/index'
import { Route as SignedInOrganizationSlugRouteRouteImport } from './routes/_signed-in/$organizationSlug/route'
import { Route as SignedInOrganizationsRouteImport } from './routes/_signed-in/organizations'
import { Route as SignedInOrganizationSlugIndexRouteImport } from './routes/_signed-in/$organizationSlug/index'
import { Route as SignedInOrganizationSlugCoursesCourseIdIndexRouteImport } from './routes/_signed-in/$organizationSlug/courses/$courseId/index'
import { Route as SignedInOrganizationSlugCoursesCourseIdLearnersLearnerIdRouteImport } from './routes/_signed-in/$organizationSlug/courses/$courseId/learners/$learnerId'

const SignedInRouteRoute = SignedInRouteRouteImport.update({
  id: '/_signed-in',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignedInIndexRoute = SignedInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignedInRouteRoute,
} as any)
const SignedInOrganizationSlugRouteRoute =
  SignedInOrganizationSlugRouteRouteImport.update({
    id: '/$organizationSlug',
    path: '/$organizationSlug',
    getParentRoute: () => SignedInRouteRoute,
  } as any)
const SignedInOrganizationsRoute = SignedInOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => SignedInRouteRoute,
} as any)
const SignedInOrganizationSlugIndexRoute =
  SignedInOrganizationSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SignedInOrganizationSlugRouteRoute,
  } as any)
const SignedInOrganizationSlugCoursesCourseIdIndexRoute =
  SignedInOrganizationSlugCoursesCourseIdIndexRouteImport.update({
    id: '/courses/$courseId/',
    path: '/courses/$courseId/',
    getParentRoute: () => SignedInOrganizationSlugRouteRoute,
  } as any)
const SignedInOrganizationSlugCoursesCourseIdLearnersLearnerIdRoute =
  SignedInOrganizationSlugCoursesCourseIdLearnersLearnerIdRouteImport.update({
    id: '/courses/$courseId/learners/$learnerId',
    path: '/courses/$courseId/learners/$learnerId',
    getParentRoute: () => SignedInOrganizationSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SignedInIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$organizationSlug': typeof SignedInOrganizationSlugRouteRouteWithChildren
  '/organizations': typeof SignedInOrganizationsRoute
  '/$organizationSlug/': typeof SignedInOrganizationSlugIndexRoute
  '/$organizationSlug/courses/$courseId/': typeof SignedInOrganizationSlugCoursesCourseIdIndexRoute
  '/$organizationSlug/courses/$courseId/learners/$learnerId': typeof SignedInOrganizationSlugCoursesCourseIdLearnersLearnerIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/organizations': typeof SignedInOrganizationsRoute
  '/': typeof SignedInIndexRoute
  '/$organizationSlug': typeof SignedInOrganizationSlugIndexRoute
  '/$organizationSlug/courses/$courseId': typeof SignedInOrganizationSlugCoursesCourseIdIndexRoute
  '/$organizationSlug/courses/$courseId/learners/$learnerId': typeof SignedInOrganizationSlugCoursesCourseIdLearnersLearnerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_signed-in': typeof SignedInRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_signed-in/$organizationSlug': typeof SignedInOrganizationSlugRouteRouteWithChildren
  '/_signed-in/organizations': typeof SignedInOrganizationsRoute
  '/_signed-in/': typeof SignedInIndexRoute
  '/_signed-in/$organizationSlug/': typeof SignedInOrganizationSlugIndexRoute
  '/_signed-in/$organizationSlug/courses/$courseId/': typeof SignedInOrganizationSlugCoursesCourseIdIndexRoute
  '/_signed-in/$organizationSlug/courses/$courseId/learners/$learnerId': typeof SignedInOrganizationSlugCoursesCourseIdLearnersLearnerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/$organizationSlug'
    | '/organizations'
    | '/$organizationSlug/'
    | '/$organizationSlug/courses/$courseId/'
    | '/$organizationSlug/courses/$courseId/learners/$learnerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/organizations'
    | '/'
    | '/$organizationSlug'
    | '/$organizationSlug/courses/$courseId'
    | '/$organizationSlug/courses/$courseId/learners/$learnerId'
  id:
    | '__root__'
    | '/_signed-in'
    | '/login'
    | '/signup'
    | '/_signed-in/$organizationSlug'
    | '/_signed-in/organizations'
    | '/_signed-in/'
    | '/_signed-in/$organizationSlug/'
    | '/_signed-in/$organizationSlug/courses/$courseId/'
    | '/_signed-in/$organizationSlug/courses/$courseId/learners/$learnerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SignedInRouteRoute: typeof SignedInRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_signed-in': {
      id: '/_signed-in'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SignedInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_signed-in/': {
      id: '/_signed-in/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SignedInIndexRouteImport
      parentRoute: typeof SignedInRouteRoute
    }
    '/_signed-in/$organizationSlug': {
      id: '/_signed-in/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof SignedInOrganizationSlugRouteRouteImport
      parentRoute: typeof SignedInRouteRoute
    }
    '/_signed-in/organizations': {
      id: '/_signed-in/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof SignedInOrganizationsRouteImport
      parentRoute: typeof SignedInRouteRoute
    }
    '/_signed-in/$organizationSlug/': {
      id: '/_signed-in/$organizationSlug/'
      path: '/'
      fullPath: '/$organizationSlug/'
      preLoaderRoute: typeof SignedInOrganizationSlugIndexRouteImport
      parentRoute: typeof SignedInOrganizationSlugRouteRoute
    }
    '/_signed-in/$organizationSlug/courses/$courseId/': {
      id: '/_signed-in/$organizationSlug/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/$organizationSlug/courses/$courseId/'
      preLoaderRoute: typeof SignedInOrganizationSlugCoursesCourseIdIndexRouteImport
      parentRoute: typeof SignedInOrganizationSlugRouteRoute
    }
    '/_signed-in/$organizationSlug/courses/$courseId/learners/$learnerId': {
      id: '/_signed-in/$organizationSlug/courses/$courseId/learners/$learnerId'
      path: '/courses/$courseId/learners/$learnerId'
      fullPath: '/$organizationSlug/courses/$courseId/learners/$learnerId'
      preLoaderRoute: typeof SignedInOrganizationSlugCoursesCourseIdLearnersLearnerIdRouteImport
      parentRoute: typeof SignedInOrganizationSlugRouteRoute
    }
  }
}

interface SignedInOrganizationSlugRouteRouteChildren {
  SignedInOrganizationSlugIndexRoute: typeof SignedInOrganizationSlugIndexRoute
  SignedInOrganizationSlugCoursesCourseIdIndexRoute: typeof SignedInOrganizationSlugCoursesCourseIdIndexRoute
  SignedInOrganizationSlugCoursesCourseIdLearnersLearnerIdRoute: typeof SignedInOrganizationSlugCoursesCourseIdLearnersLearnerIdRoute
}

const SignedInOrganizationSlugRouteRouteChildren: SignedInOrganizationSlugRouteRouteChildren =
  {
    SignedInOrganizationSlugIndexRoute: SignedInOrganizationSlugIndexRoute,
    SignedInOrganizationSlugCoursesCourseIdIndexRoute:
      SignedInOrganizationSlugCoursesCourseIdIndexRoute,
    SignedInOrganizationSlugCoursesCourseIdLearnersLearnerIdRoute:
      SignedInOrganizationSlugCoursesCourseIdLearnersLearnerIdRoute,
  }

const SignedInOrganizationSlugRouteRouteWithChildren =
  SignedInOrganizationSlugRouteRoute._addFileChildren(
    SignedInOrganizationSlugRouteRouteChildren,
  )

interface SignedInRouteRouteChildren {
  SignedInOrganizationSlugRouteRoute: typeof SignedInOrganizationSlugRouteRouteWithChildren
  SignedInOrganizationsRoute: typeof SignedInOrganizationsRoute
  SignedInIndexRoute: typeof SignedInIndexRoute
}

const SignedInRouteRouteChildren: SignedInRouteRouteChildren = {
  SignedInOrganizationSlugRouteRoute:
    SignedInOrganizationSlugRouteRouteWithChildren,
  SignedInOrganizationsRoute: SignedInOrganizationsRoute,
  SignedInIndexRoute: SignedInIndexRoute,
}

const SignedInRouteRouteWithChildren = SignedInRouteRoute._addFileChildren(
  SignedInRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SignedInRouteRoute: SignedInRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
